// Package service provides business services for the SDK
package service

import (
	"context"
	"strings"

	"github.com/Jayj1997/higress-admin-sdk-golang/internal/kubernetes"
	"github.com/Jayj1997/higress-admin-sdk-golang/pkg/errors"
	"github.com/Jayj1997/higress-admin-sdk-golang/pkg/model"
)

// TlsCertificateService TLS证书管理服务接口
type TlsCertificateService interface {
	// List 列出TLS证书
	List(ctx context.Context, query *model.CommonPageQuery) (*model.PaginatedResult[model.TlsCertificate], error)

	// Get 根据名称获取证书
	Get(ctx context.Context, name string) (*model.TlsCertificate, error)

	// Add 添加证书
	Add(ctx context.Context, cert *model.TlsCertificate) (*model.TlsCertificate, error)

	// Update 更新证书
	Update(ctx context.Context, cert *model.TlsCertificate) (*model.TlsCertificate, error)

	// Delete 删除证书
	Delete(ctx context.Context, name string) error
}

// TlsCertificateServiceImpl TLS证书服务实现
type TlsCertificateServiceImpl struct {
	kubernetesClient *kubernetes.KubernetesClientService
	modelConverter   *kubernetes.KubernetesModelConverter
}

// NewTlsCertificateService 创建TLS证书服务实例
func NewTlsCertificateService(
	kubernetesClient *kubernetes.KubernetesClientService,
	modelConverter *kubernetes.KubernetesModelConverter,
) TlsCertificateService {
	return &TlsCertificateServiceImpl{
		kubernetesClient: kubernetesClient,
		modelConverter:   modelConverter,
	}
}

// List 列出TLS证书
func (s *TlsCertificateServiceImpl) List(ctx context.Context, query *model.CommonPageQuery) (*model.PaginatedResult[model.TlsCertificate], error) {
	secrets, err := s.kubernetesClient.ListSecrets(ctx, "kubernetes.io/tls")
	if err != nil {
		return nil, errors.NewBusinessError("Error occurs when listing Secret: " + err.Error())
	}

	// 转换为TlsCertificate列表
	certs := make([]model.TlsCertificate, 0, len(secrets))
	for i := range secrets {
		cert, err := s.modelConverter.SecretToTlsCertificate(&secrets[i])
		if err != nil {
			// 记录错误但继续处理其他证书
			continue
		}
		certs = append(certs, *cert)
	}

	// 应用分页
	total := len(certs)
	pageNum := 1
	pageSize := 10
	if query != nil {
		pageNum = query.PageNum
		pageSize = query.GetPageSize()
	}

	// 计算分页
	start := (pageNum - 1) * pageSize
	end := start + pageSize
	if start > total {
		start = total
	}
	if end > total {
		end = total
	}

	pagedData := certs[start:end]
	return model.NewPaginatedResult(pagedData, total, pageNum, pageSize), nil
}

// Get 根据名称获取证书
func (s *TlsCertificateServiceImpl) Get(ctx context.Context, name string) (*model.TlsCertificate, error) {
	secret, err := s.kubernetesClient.GetSecret(ctx, name)
	if err != nil {
		return nil, errors.NewBusinessError("Error occurs when reading the Secret with name: " + name)
	}

	if secret == nil {
		return nil, nil
	}

	// 验证Secret类型
	if secret.Type != "kubernetes.io/tls" {
		return nil, nil
	}

	return s.modelConverter.SecretToTlsCertificate(secret)
}

// Add 添加证书
func (s *TlsCertificateServiceImpl) Add(ctx context.Context, cert *model.TlsCertificate) (*model.TlsCertificate, error) {
	secret, err := s.modelConverter.TlsCertificateToSecret(cert)
	if err != nil {
		return nil, err
	}

	newSecret, err := s.kubernetesClient.CreateSecret(ctx, secret)
	if err != nil {
		// 检查是否是冲突错误
		if strings.Contains(err.Error(), "409") || strings.Contains(err.Error(), "AlreadyExists") {
			return nil, errors.NewResourceConflictError("TlsCertificate", cert.Name)
		}
		return nil, errors.NewBusinessError("Error occurs when creating the secret generated by tls certificate with name: " + cert.Name)
	}

	return s.modelConverter.SecretToTlsCertificate(newSecret)
}

// Update 更新证书
func (s *TlsCertificateServiceImpl) Update(ctx context.Context, cert *model.TlsCertificate) (*model.TlsCertificate, error) {
	secret, err := s.modelConverter.TlsCertificateToSecret(cert)
	if err != nil {
		return nil, err
	}

	newSecret, err := s.kubernetesClient.UpdateSecret(ctx, secret)
	if err != nil {
		// 检查是否是冲突错误
		if strings.Contains(err.Error(), "409") || strings.Contains(err.Error(), "Conflict") {
			return nil, errors.NewResourceConflictError("TlsCertificate", cert.Name)
		}
		return nil, errors.NewBusinessError("Error occurs when updating the secret generated by tls certificate with name: " + cert.Name)
	}

	return s.modelConverter.SecretToTlsCertificate(newSecret)
}

// Delete 删除证书
func (s *TlsCertificateServiceImpl) Delete(ctx context.Context, name string) error {
	err := s.kubernetesClient.DeleteSecret(ctx, name)
	if err != nil {
		return errors.NewBusinessError("Error occurs when deleting the Secret with name: " + name)
	}
	return nil
}
